// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVurRny-s_Yu4Xkfbw_t-059IObhCAfgA',
    appId: '1:538450085385:web:c4b3d7a60ed20f6df69ad8',
    messagingSenderId: '538450085385',
    projectId: 'fauzi-flutter',
    authDomain: 'fauzi-flutter.firebaseapp.com',
    storageBucket: 'fauzi-flutter.firebasestorage.app',
    measurementId: 'G-436GEYCDBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJNH08DUZiJfDrvnKgpJ0Ky5m8ULR_nM8',
    appId: '1:538450085385:android:575428e3170901b6f69ad8',
    messagingSenderId: '538450085385',
    projectId: 'fauzi-flutter',
    storageBucket: 'fauzi-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArsOf6_nl-9p4IvemkzJoqCjjr327xokM',
    appId: '1:538450085385:ios:1ad05c93e6ee0ad9f69ad8',
    messagingSenderId: '538450085385',
    projectId: 'fauzi-flutter',
    storageBucket: 'fauzi-flutter.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArsOf6_nl-9p4IvemkzJoqCjjr327xokM',
    appId: '1:538450085385:ios:1ad05c93e6ee0ad9f69ad8',
    messagingSenderId: '538450085385',
    projectId: 'fauzi-flutter',
    storageBucket: 'fauzi-flutter.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVurRny-s_Yu4Xkfbw_t-059IObhCAfgA',
    appId: '1:538450085385:web:e63acc92240313b9f69ad8',
    messagingSenderId: '538450085385',
    projectId: 'fauzi-flutter',
    authDomain: 'fauzi-flutter.firebaseapp.com',
    storageBucket: 'fauzi-flutter.firebasestorage.app',
    measurementId: 'G-3Y4054N6W0',
  );
}
